# jmeter master
---
kind: Service
apiVersion: v1
metadata:
  name: jmeter-master
  labels:
    app: jmeter-master
spec:
  selector:
    app: jmeter-master
  ports:
    - protocol: TCP
      name: metrics
      port: 9270
      targetPort: 9270
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    app: jmeter-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
        - name: jmeter-master
          image: mx2542/kakax-jmeter:latest
          command: ["sleep"]
          args: ["infinity"]
          ports:
            - containerPort: 9270
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /jmx
              name: jmx
          env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: admin-user-token
      volumes:
        - name: jmx
          persistentVolumeClaim:
            claimName: jmx-nfs-pvc

# jmeter slave
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slave
  labels:
    app: jmeter-slave
spec:
  ports:
    - port: 1099
      targetPort: 1099
  clusterIP: None
  selector:
    app: jmeter-slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jmeter-slave
spec:
  selector:
    matchLabels:
      app: jmeter-slave
  serviceName: "jmeter-slave"
  replicas: 2
  template:
    metadata:
      labels:
        app: jmeter-slave
    spec:
      containers:
        - name: jmeter-slave
          image: mx2542/kakax-jmeter:latest
          command: ["./apache-jmeter-5.4.3/bin/jmeter-server"]
          ports:
            - containerPort: 1099
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /jmx
              name: jmx
          env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: admin-user-token
      volumes:
        - name: jmx
          persistentVolumeClaim:
            claimName: jmx-nfs-pvc
