kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
  extraPortMappings:
    - containerPort: 5000
      hostPort: 5000
      protocol: TCP
    - containerPort: 30081
      hostPort: 30081
      protocol: TCP
    - containerPort: 30777
      hostPort: 30777
      protocol: TCP
    - containerPort: 32763
      hostPort: 32763
      protocol: TCP

