name: test
on:
  push:
    branches:
      - master
      - main
      - release-*
  pull_request:
    branches:
      - master
      - main
      - release-*
jobs:
  test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: .github/workflows/kind/kind.yaml

      - name: Install
        run: |
          sh scripts/install.sh 

      # - name: Run e2e test
      #   run: |
      #     cd tests/e2e
      #     npm install
      #     npm run test

      - name: Uninstall
        run: |
          sh scripts/uninstall.sh 
